// Brand Color Database
// Each brand page = an indexed URL targeting "[brand] colors hex"

export interface BrandColor {
  name: string;
  hex: string;
  usage: string; // e.g. "Primary", "Secondary", "Accent"
}

export interface Brand {
  slug: string;
  name: string;
  industry: string;
  colors: BrandColor[];
  story: string; // Why they chose those colors
  founded: string;
  website: string;
}

export const INDUSTRIES = [
  "All",
  "Tech",
  "Social Media",
  "Food & Beverage",
  "Fashion & Retail",
  "Gaming",
  "Automotive",
  "Entertainment",
  "Finance",
  "Sports",
  "Health & Beauty",
  "Travel & Airlines",
  "Media",
] as const;

export const BRANDS: Brand[] = [
  // ─── Tech ──────────────────────────────────────────
  {
    slug: "apple",
    name: "Apple",
    industry: "Tech",
    colors: [
      { name: "Black", hex: "#000000", usage: "Primary" },
      { name: "Silver", hex: "#A2AAAD", usage: "Secondary" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Blue", hex: "#0071E3", usage: "Link/CTA" },
      { name: "Green", hex: "#4CD964", usage: "Success" },
    ],
    story: "Apple's minimalist palette reflects its design philosophy: simplicity, elegance, and premium quality. The shift from rainbow to monochrome in 1998 signaled the brand's evolution toward sophistication. Black conveys luxury, while the signature blue is reserved for interactive elements.",
    founded: "1976",
    website: "apple.com",
  },
  {
    slug: "google",
    name: "Google",
    industry: "Tech",
    colors: [
      { name: "Blue", hex: "#4285F4", usage: "Primary" },
      { name: "Red", hex: "#EA4335", usage: "Secondary" },
      { name: "Yellow", hex: "#FBBC05", usage: "Accent" },
      { name: "Green", hex: "#34A853", usage: "Accent" },
      { name: "Gray", hex: "#5F6368", usage: "Text" },
    ],
    story: "Google's four-color palette (blue, red, yellow, green) was designed to feel playful and approachable. The colors follow a pattern — but break it intentionally (the 'l' in green instead of following the RGB sequence) to show Google doesn't follow rules.",
    founded: "1998",
    website: "google.com",
  },
  {
    slug: "microsoft",
    name: "Microsoft",
    industry: "Tech",
    colors: [
      { name: "Red", hex: "#F25022", usage: "Primary" },
      { name: "Green", hex: "#7FBA00", usage: "Primary" },
      { name: "Blue", hex: "#00A4EF", usage: "Primary" },
      { name: "Yellow", hex: "#FFB900", usage: "Primary" },
      { name: "Gray", hex: "#737373", usage: "Text" },
    ],
    story: "Microsoft's four-square logo represents the diversity of their product ecosystem — Windows (blue), Office (red), Xbox (green), and the broader platform (yellow). The 2012 redesign flattened the colors for a modern, clean aesthetic aligned with Windows 8's Metro design language.",
    founded: "1975",
    website: "microsoft.com",
  },
  {
    slug: "amazon",
    name: "Amazon",
    industry: "Tech",
    colors: [
      { name: "Black", hex: "#000000", usage: "Primary" },
      { name: "Orange", hex: "#FF9900", usage: "Accent" },
      { name: "Blue", hex: "#146EB4", usage: "Link" },
      { name: "Light Gray", hex: "#F3F3F3", usage: "Background" },
      { name: "Dark Blue", hex: "#232F3E", usage: "Footer" },
    ],
    story: "Amazon's orange arrow (the 'smile' from A to Z) represents the happiness of delivery and the fact they sell everything from A to Z. The orange is warm and inviting — signaling affordability and customer focus. The dark blue footer conveys trust.",
    founded: "1994",
    website: "amazon.com",
  },
  {
    slug: "meta",
    name: "Meta",
    industry: "Tech",
    colors: [
      { name: "Meta Blue", hex: "#0668E1", usage: "Primary" },
      { name: "Facebook Blue", hex: "#1877F2", usage: "Facebook" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Gray", hex: "#65676B", usage: "Text" },
      { name: "Light Gray", hex: "#F0F2F5", usage: "Surface" },
    ],
    story: "Meta's blue was inherited from Facebook, which Mark Zuckerberg chose because he's red-green colorblind — blue is the color he sees best. The rebranding to Meta introduced a slightly different blue and an infinity-loop logo to represent the metaverse.",
    founded: "2004",
    website: "meta.com",
  },
  {
    slug: "github",
    name: "GitHub",
    industry: "Tech",
    colors: [
      { name: "Black", hex: "#24292E", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Blue", hex: "#0366D6", usage: "Link" },
      { name: "Green", hex: "#2EA44F", usage: "CTA/Success" },
      { name: "Gray", hex: "#586069", usage: "Text" },
    ],
    story: "GitHub's dark palette reflects its developer audience — familiar with dark terminals and code editors. The signature green button ('Create', 'Merge') signals positive action, while the minimal palette keeps focus on code, not chrome.",
    founded: "2008",
    website: "github.com",
  },
  {
    slug: "slack",
    name: "Slack",
    industry: "Tech",
    colors: [
      { name: "Aubergine", hex: "#4A154B", usage: "Primary" },
      { name: "Blue", hex: "#36C5F0", usage: "Accent" },
      { name: "Green", hex: "#2EB67D", usage: "Accent" },
      { name: "Red", hex: "#E01E5A", usage: "Accent" },
      { name: "Yellow", hex: "#ECB22E", usage: "Accent" },
    ],
    story: "Slack's four-color accent palette atop the deep aubergine creates a sense of organized fun — professional but not corporate. The 2019 rebrand simplified the colors to be more accessible and consistently reproducible across all media.",
    founded: "2013",
    website: "slack.com",
  },

  // ─── Social Media ──────────────────────────────────
  {
    slug: "spotify",
    name: "Spotify",
    industry: "Social Media",
    colors: [
      { name: "Green", hex: "#1DB954", usage: "Primary" },
      { name: "Black", hex: "#191414", usage: "Background" },
      { name: "White", hex: "#FFFFFF", usage: "Text" },
      { name: "Dark Gray", hex: "#282828", usage: "Surface" },
      { name: "Light Gray", hex: "#B3B3B3", usage: "Secondary Text" },
    ],
    story: "Spotify's green stands out in a sea of blue tech logos. It represents growth, energy, and the freshness of discovering new music. The dark UI puts album art front and center — the colors don't compete with the content.",
    founded: "2006",
    website: "spotify.com",
  },
  {
    slug: "netflix",
    name: "Netflix",
    industry: "Entertainment",
    colors: [
      { name: "Red", hex: "#E50914", usage: "Primary" },
      { name: "Black", hex: "#141414", usage: "Background" },
      { name: "White", hex: "#FFFFFF", usage: "Text" },
      { name: "Dark Gray", hex: "#221F1F", usage: "Surface" },
      { name: "Gray", hex: "#808080", usage: "Secondary" },
    ],
    story: "Netflix's red is cinematic — evoking the red curtain of a movie theater. Against the black background, it creates a premium, immersive viewing experience. The minimal palette ensures content thumbnails are the visual focus.",
    founded: "1997",
    website: "netflix.com",
  },
  {
    slug: "twitter",
    name: "X (Twitter)",
    industry: "Social Media",
    colors: [
      { name: "Black", hex: "#000000", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Blue", hex: "#1D9BF0", usage: "Legacy Blue" },
      { name: "Dark Gray", hex: "#0F1419", usage: "Text" },
      { name: "Gray", hex: "#536471", usage: "Secondary" },
    ],
    story: "The original Twitter blue represented open communication, like a clear sky. After the rebrand to X, the palette shifted to stark black and white — signaling a new era. The legacy blue persists in verified badges and links.",
    founded: "2006",
    website: "x.com",
  },
  {
    slug: "instagram",
    name: "Instagram",
    industry: "Social Media",
    colors: [
      { name: "Gradient Start", hex: "#833AB4", usage: "Primary" },
      { name: "Gradient Mid", hex: "#FD1D1D", usage: "Primary" },
      { name: "Gradient End", hex: "#FCAF45", usage: "Primary" },
      { name: "Dark", hex: "#262626", usage: "Text" },
      { name: "Blue", hex: "#0095F6", usage: "Link/CTA" },
    ],
    story: "Instagram's purple-red-orange gradient represents the sunset — the golden hour that photographers chase. The gradient also nods to the diversity of content on the platform. The blue CTA buttons draw from parent company Meta's palette.",
    founded: "2010",
    website: "instagram.com",
  },
  {
    slug: "tiktok",
    name: "TikTok",
    industry: "Social Media",
    colors: [
      { name: "Black", hex: "#010101", usage: "Primary" },
      { name: "Cyan", hex: "#25F4EE", usage: "Accent" },
      { name: "Red", hex: "#FE2C55", usage: "Accent" },
      { name: "White", hex: "#FFFFFF", usage: "Text" },
      { name: "Gray", hex: "#161823", usage: "Background" },
    ],
    story: "TikTok's cyan and red create a 3D anaglyph effect — reminiscent of retro 3D glasses. This duality represents the app's ability to merge reality with creative expression. The dark background keeps focus on video content.",
    founded: "2016",
    website: "tiktok.com",
  },
  {
    slug: "youtube",
    name: "YouTube",
    industry: "Social Media",
    colors: [
      { name: "Red", hex: "#FF0000", usage: "Primary" },
      { name: "Black", hex: "#282828", usage: "Background" },
      { name: "White", hex: "#FFFFFF", usage: "Text/Background" },
      { name: "Dark", hex: "#0F0F0F", usage: "Dark Mode" },
      { name: "Gray", hex: "#AAAAAA", usage: "Secondary" },
    ],
    story: "YouTube's red play button is one of the most recognized icons on the internet. The red conveys energy, passion, and entertainment. Like Netflix, the dark UI puts video thumbnails first — the platform is about the content, not the chrome.",
    founded: "2005",
    website: "youtube.com",
  },
  {
    slug: "linkedin",
    name: "LinkedIn",
    industry: "Social Media",
    colors: [
      { name: "Blue", hex: "#0A66C2", usage: "Primary" },
      { name: "Black", hex: "#000000", usage: "Text" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Light Blue", hex: "#70B5F9", usage: "Accent" },
      { name: "Gray", hex: "#86888A", usage: "Secondary" },
    ],
    story: "LinkedIn's blue represents trust, professionalism, and reliability — essential qualities for a professional network. It's a deeper, more serious blue than Facebook or Twitter, positioning LinkedIn as the grown-up in the social media room.",
    founded: "2003",
    website: "linkedin.com",
  },
  {
    slug: "discord",
    name: "Discord",
    industry: "Social Media",
    colors: [
      { name: "Blurple", hex: "#5865F2", usage: "Primary" },
      { name: "Green", hex: "#57F287", usage: "Online/Success" },
      { name: "Yellow", hex: "#FEE75C", usage: "Warning/Idle" },
      { name: "Red", hex: "#ED4245", usage: "Error/DND" },
      { name: "Dark", hex: "#2C2F33", usage: "Background" },
    ],
    story: "Discord coined 'blurple' — a blue-purple that feels both technical and playful. The color system directly maps to status: green (online), yellow (idle), red (do not disturb). The 2021 rebrand made the blurple slightly more saturated and vibrant.",
    founded: "2015",
    website: "discord.com",
  },
  {
    slug: "snapchat",
    name: "Snapchat",
    industry: "Social Media",
    colors: [
      { name: "Yellow", hex: "#FFFC00", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Ghost" },
      { name: "Black", hex: "#000000", usage: "Text" },
      { name: "Purple", hex: "#9B5DE5", usage: "Discover" },
      { name: "Cyan", hex: "#00C4CC", usage: "Accent" },
    ],
    story: "Snapchat's bright yellow was chosen to stand out on phone screens and app stores — no other major app uses yellow as its primary. Bobby Murphy said they wanted something 'fun' that 'no one else was using.' It worked — the yellow is instantly recognizable.",
    founded: "2011",
    website: "snapchat.com",
  },
  {
    slug: "twitch",
    name: "Twitch",
    industry: "Entertainment",
    colors: [
      { name: "Purple", hex: "#9146FF", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Text/Background" },
      { name: "Dark", hex: "#0E0E10", usage: "Background" },
      { name: "Light Purple", hex: "#BF94FF", usage: "Accent" },
      { name: "Gray", hex: "#1F1F23", usage: "Surface" },
    ],
    story: "Twitch's purple signals creativity and individuality — perfect for a platform built on unique content creators. Purple is rare in tech (most go blue), which helps Twitch stand out. The dark UI reduces eye strain during long viewing sessions.",
    founded: "2011",
    website: "twitch.tv",
  },

  // ─── Food & Beverage ───────────────────────────────
  {
    slug: "coca-cola",
    name: "Coca-Cola",
    industry: "Food & Beverage",
    colors: [
      { name: "Red", hex: "#F40009", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Text/Logo" },
      { name: "Black", hex: "#000000", usage: "Accent" },
      { name: "Dark Red", hex: "#C8102E", usage: "Darker Variant" },
    ],
    story: "Coca-Cola's red is arguably the most famous brand color in the world. Originally, the barrels were painted red to distinguish them from alcohol during shipping. The color has come to represent happiness, sharing, and the American dream.",
    founded: "1886",
    website: "coca-cola.com",
  },
  {
    slug: "mcdonalds",
    name: "McDonald's",
    industry: "Food & Beverage",
    colors: [
      { name: "Yellow", hex: "#FFC72C", usage: "Primary (Golden Arches)" },
      { name: "Red", hex: "#DA291C", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Black", hex: "#27251F", usage: "Text" },
      { name: "Green", hex: "#264F36", usage: "European Rebrand" },
    ],
    story: "Red stimulates appetite and urgency. Yellow (the golden arches) signals happiness and warmth. Together, they're the most effective food color combination ever created. In Europe, McDonald's shifted to green backgrounds to project a healthier, eco-friendly image.",
    founded: "1955",
    website: "mcdonalds.com",
  },
  {
    slug: "starbucks",
    name: "Starbucks",
    industry: "Food & Beverage",
    colors: [
      { name: "Green", hex: "#00704A", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Logo/Background" },
      { name: "Black", hex: "#000000", usage: "Text" },
      { name: "Warm Gray", hex: "#D4E9E2", usage: "Light Accent" },
      { name: "Gold", hex: "#CBA258", usage: "Premium/Reserve" },
    ],
    story: "Starbucks green represents growth, freshness, and the connection to nature — the coffee plant itself. The siren logo in white on green creates an iconic, instantly recognizable mark. The gold is reserved for Starbucks Reserve and premium products.",
    founded: "1971",
    website: "starbucks.com",
  },

  // ─── Fashion & Retail ──────────────────────────────
  {
    slug: "nike",
    name: "Nike",
    industry: "Fashion & Retail",
    colors: [
      { name: "Black", hex: "#111111", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Background/Logo" },
      { name: "Nike Orange", hex: "#FA5400", usage: "Accent" },
      { name: "Volt", hex: "#C5FF00", usage: "Performance" },
      { name: "Gray", hex: "#7E7E7E", usage: "Secondary" },
    ],
    story: "Nike's power comes from black and white simplicity — letting the swoosh speak for itself. The 'Volt' green-yellow (used in performance products) was engineered to be the most visible color on a running track. Nike Orange adds energy for marketing campaigns.",
    founded: "1964",
    website: "nike.com",
  },
  {
    slug: "adidas",
    name: "Adidas",
    industry: "Fashion & Retail",
    colors: [
      { name: "Black", hex: "#000000", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Logo/Background" },
      { name: "Blue", hex: "#0066B2", usage: "Originals" },
      { name: "Red", hex: "#EF3340", usage: "Performance" },
      { name: "Green", hex: "#00A651", usage: "Sustainability" },
    ],
    story: "Adidas uses black as its foundation — the three stripes are iconic in any color. Blue represents Adidas Originals (heritage), while the performance line uses red for energy. The green signals their commitment to sustainability with recycled materials.",
    founded: "1949",
    website: "adidas.com",
  },
  {
    slug: "ikea",
    name: "IKEA",
    industry: "Fashion & Retail",
    colors: [
      { name: "Blue", hex: "#0058A3", usage: "Primary" },
      { name: "Yellow", hex: "#FFDA1A", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Black", hex: "#111111", usage: "Text" },
      { name: "Red", hex: "#CC0008", usage: "Sale/Accent" },
    ],
    story: "IKEA's blue and yellow come directly from the Swedish flag — founder Ingvar Kamprad wanted the brand to be unmistakably Swedish. Blue conveys trust and reliability, yellow conveys warmth and optimism. Together they signal: affordable quality from Sweden.",
    founded: "1943",
    website: "ikea.com",
  },

  // ─── Gaming ────────────────────────────────────────
  {
    slug: "nintendo",
    name: "Nintendo",
    industry: "Gaming",
    colors: [
      { name: "Red", hex: "#E60012", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Logo/Background" },
      { name: "Gray", hex: "#8F8F8F", usage: "Hardware" },
      { name: "Neon Blue", hex: "#00C3E3", usage: "Switch (Left)" },
      { name: "Neon Red", hex: "#FF3C28", usage: "Switch (Right)" },
    ],
    story: "Nintendo's red represents the joy, energy, and fun at the heart of gaming. The Switch's neon blue and red Joy-Cons were designed to feel playful and invite multiplayer — two colors, two controllers, two players. Nintendo proves gaming doesn't need to be dark and edgy.",
    founded: "1889",
    website: "nintendo.com",
  },
  {
    slug: "playstation",
    name: "PlayStation",
    industry: "Gaming",
    colors: [
      { name: "Blue", hex: "#003791", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Logo" },
      { name: "Black", hex: "#000000", usage: "Hardware" },
      { name: "Blue Light", hex: "#00439C", usage: "PS5 Light" },
      { name: "Purple", hex: "#6B37FF", usage: "PS Plus" },
    ],
    story: "PlayStation's blue represents depth and immersion — diving into game worlds. The PS5's striking white-and-black hardware broke from the all-black tradition, but the blue light bar kept the brand identity. The purple for PS Plus signals premium and exclusivity.",
    founded: "1994",
    website: "playstation.com",
  },
  {
    slug: "xbox",
    name: "Xbox",
    industry: "Gaming",
    colors: [
      { name: "Green", hex: "#107C10", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Black", hex: "#000000", usage: "Hardware" },
      { name: "Light Green", hex: "#84C447", usage: "Accent" },
      { name: "Gray", hex: "#767676", usage: "Secondary" },
    ],
    story: "Xbox green was chosen to stand apart from PlayStation's blue. Green represents power, energy, and the 'go' signal — jump in and play. The original Xbox's green X became one of gaming's most iconic symbols, and Microsoft has kept the green consistent across 20+ years.",
    founded: "2001",
    website: "xbox.com",
  },
  {
    slug: "steam",
    name: "Steam",
    industry: "Gaming",
    colors: [
      { name: "Dark Blue", hex: "#171A21", usage: "Background" },
      { name: "Blue", hex: "#1B2838", usage: "Surface" },
      { name: "Light Blue", hex: "#66C0F4", usage: "Accent" },
      { name: "Green", hex: "#4C6B22", usage: "Sale/Discount" },
      { name: "White", hex: "#C7D5E0", usage: "Text" },
    ],
    story: "Steam's dark blue palette creates a storefront that lets game artwork pop. The signature light blue accent is used sparingly for links and highlights. Green exclusively signals discounts and sales — Pavlovian conditioning for Steam Sale excitement.",
    founded: "2003",
    website: "store.steampowered.com",
  },

  // ─── Automotive ────────────────────────────────────
  {
    slug: "tesla",
    name: "Tesla",
    industry: "Automotive",
    colors: [
      { name: "Red", hex: "#CC0000", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Black", hex: "#000000", usage: "Text" },
      { name: "Silver", hex: "#5C5C5C", usage: "Metallic Accent" },
      { name: "Blue", hex: "#3457D5", usage: "UI Accent" },
    ],
    story: "Tesla's red represents the passion and disruption Elon Musk brought to the auto industry. The minimal black-and-white palette of their website mirrors the clean, tech-forward design of their cars. Tesla proves an electric car brand can feel exciting, not boring.",
    founded: "2003",
    website: "tesla.com",
  },
  {
    slug: "ferrari",
    name: "Ferrari",
    industry: "Automotive",
    colors: [
      { name: "Rosso Corsa", hex: "#FF2800", usage: "Primary" },
      { name: "Yellow", hex: "#FFD700", usage: "Shield" },
      { name: "Black", hex: "#000000", usage: "Text/Accent" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Green", hex: "#008C45", usage: "Italian Flag" },
    ],
    story: "Ferrari's Rosso Corsa (racing red) dates back to early 1900s Grand Prix racing when Italian cars were mandated red. The prancing horse on a yellow shield comes from a WWI fighter ace. Together, these colors are synonymous with speed, luxury, and Italian passion.",
    founded: "1947",
    website: "ferrari.com",
  },

  // ─── Finance ───────────────────────────────────────
  {
    slug: "stripe",
    name: "Stripe",
    industry: "Finance",
    colors: [
      { name: "Purple", hex: "#635BFF", usage: "Primary" },
      { name: "Cyan", hex: "#00D4AA", usage: "Accent" },
      { name: "Blue", hex: "#0A2540", usage: "Dark Background" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Gray", hex: "#425466", usage: "Text" },
    ],
    story: "Stripe's purple breaks from the blue-dominated fintech space. It signals innovation and a developer-first approach. The gradient meshes and vivid color combinations in their marketing set a new standard for fintech design — proving financial tools don't have to look boring.",
    founded: "2010",
    website: "stripe.com",
  },
  {
    slug: "paypal",
    name: "PayPal",
    industry: "Finance",
    colors: [
      { name: "Dark Blue", hex: "#003087", usage: "Primary" },
      { name: "Blue", hex: "#009CDE", usage: "Secondary" },
      { name: "Light Blue", hex: "#012169", usage: "Accent" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Gray", hex: "#6C7378", usage: "Text" },
    ],
    story: "PayPal's dual-blue palette projects trust and security — essential for a company handling billions in transactions. The overlapping 'P' letters in different blues suggest connection and partnership. Blue has been PayPal's color since its founding, reinforcing reliability.",
    founded: "1998",
    website: "paypal.com",
  },

  // ─── Tech (additional) ──────────────────────────────
  {
    slug: "uber",
    name: "Uber",
    industry: "Tech",
    colors: [
      { name: "Black", hex: "#000000", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "UberX Blue", hex: "#276EF1", usage: "Product" },
      { name: "Green", hex: "#06C167", usage: "Uber Eats" },
      { name: "Gray", hex: "#6B6B6B", usage: "Secondary Text" },
    ],
    story: "Uber's rebrand in 2018 stripped everything down to black and white — no more atoms, no more confusing patterns. The simplicity says: we get you from A to B. The blue is reserved for interactive elements and safety features.",
    founded: "2009",
    website: "uber.com",
  },
  {
    slug: "airbnb",
    name: "Airbnb",
    industry: "Tech",
    colors: [
      { name: "Rausch", hex: "#FF5A5F", usage: "Primary" },
      { name: "Babu", hex: "#00A699", usage: "Secondary" },
      { name: "Arches", hex: "#FC642D", usage: "Accent" },
      { name: "Foggy", hex: "#767676", usage: "Text" },
      { name: "Hof", hex: "#484848", usage: "Dark Text" },
    ],
    story: "Airbnb's coral pink ('Rausch', named after their first street) represents belonging and warmth. The Bélo logo symbolizes people, places, love, and Airbnb forming a heart/location pin. The warm palette makes strangers' homes feel inviting.",
    founded: "2008",
    website: "airbnb.com",
  },
  {
    slug: "shopify",
    name: "Shopify",
    industry: "Tech",
    colors: [
      { name: "Green", hex: "#96BF48", usage: "Primary" },
      { name: "Dark Green", hex: "#5E8E3E", usage: "Primary Dark" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Dark", hex: "#212326", usage: "Text" },
      { name: "Purple", hex: "#7B2D8E", usage: "Accent" },
    ],
    story: "Shopify's green represents growth, commerce, and money — the exact things merchants come to Shopify for. The green shopping bag logo is instantly recognizable. Their 2023 rebrand leaned into darker tones to signal maturity while keeping the optimistic green.",
    founded: "2006",
    website: "shopify.com",
  },
  {
    slug: "notion",
    name: "Notion",
    industry: "Tech",
    colors: [
      { name: "Black", hex: "#000000", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Warm Gray", hex: "#F7F6F3", usage: "Canvas" },
      { name: "Brown", hex: "#9F6B53", usage: "Icon Accent" },
      { name: "Light Gray", hex: "#E3E2DE", usage: "Border" },
    ],
    story: "Notion's almost-monochrome palette lets your content be the color. The warm paper-like background (not cold white) makes it feel like a premium notebook. The intentional lack of color says: this is a tool, not a toy. Your ideas are what matter.",
    founded: "2013",
    website: "notion.so",
  },
  {
    slug: "figma",
    name: "Figma",
    industry: "Tech",
    colors: [
      { name: "Red", hex: "#F24E1E", usage: "Primary" },
      { name: "Orange", hex: "#FF7262", usage: "Secondary" },
      { name: "Purple", hex: "#A259FF", usage: "Accent" },
      { name: "Green", hex: "#0ACF83", usage: "Success" },
      { name: "Blue", hex: "#1ABCFE", usage: "Info" },
    ],
    story: "Figma's multi-color logo represents collaboration — each overlapping shape is a different person working on the same design. The colors are vibrant and distinct, easy to tell apart at any size. This palette helped Figma stand out from Sketch's monochrome diamond.",
    founded: "2012",
    website: "figma.com",
  },
  {
    slug: "dropbox",
    name: "Dropbox",
    industry: "Tech",
    colors: [
      { name: "Blue", hex: "#0061FF", usage: "Primary" },
      { name: "Purple", hex: "#6C3FEE", usage: "Accent" },
      { name: "Pink", hex: "#FF3585", usage: "Accent" },
      { name: "Yellow", hex: "#FFC426", usage: "Accent" },
      { name: "Coral", hex: "#FF6242", usage: "Accent" },
    ],
    story: "Dropbox's 2017 rebrand was controversial — going from clean blue to a riot of colors. The new palette represents the creative diversity of their users. Love it or hate it, it made Dropbox stand out from the sea of blue tech companies and signaled they're more than just file storage.",
    founded: "2007",
    website: "dropbox.com",
  },
  {
    slug: "openai",
    name: "OpenAI",
    industry: "Tech",
    colors: [
      { name: "Black", hex: "#000000", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Green", hex: "#10A37F", usage: "ChatGPT" },
      { name: "Light Gray", hex: "#F7F7F8", usage: "Surface" },
      { name: "Gray", hex: "#8E8EA0", usage: "Secondary" },
    ],
    story: "OpenAI's palette is deliberately understated — black and white with a single green accent for ChatGPT. The green feels approachable and safe, counterbalancing fears about AI. The minimal design says: the intelligence is the product, not the packaging.",
    founded: "2015",
    website: "openai.com",
  },

  // ─── Food & Beverage (additional) ───────────────────
  {
    slug: "pepsi",
    name: "Pepsi",
    industry: "Food & Beverage",
    colors: [
      { name: "Blue", hex: "#004B93", usage: "Primary" },
      { name: "Red", hex: "#C8102E", usage: "Accent" },
      { name: "White", hex: "#FFFFFF", usage: "Logo/Background" },
      { name: "Electric Blue", hex: "#005CB9", usage: "Digital" },
      { name: "Black", hex: "#000000", usage: "Text" },
    ],
    story: "Pepsi's blue was a deliberate move to differentiate from Coca-Cola's red. Blue represents cool, refreshing, and modern — the 'choice of a new generation.' The 2023 rebrand returned to a bolder, more saturated blue-black palette inspired by their classic 90s look.",
    founded: "1893",
    website: "pepsi.com",
  },
  {
    slug: "burger-king",
    name: "Burger King",
    industry: "Food & Beverage",
    colors: [
      { name: "Brown", hex: "#502314", usage: "Primary" },
      { name: "Red", hex: "#D62300", usage: "Secondary" },
      { name: "Yellow", hex: "#F5EBDC", usage: "Cream" },
      { name: "Orange", hex: "#FF8732", usage: "Accent" },
      { name: "Green", hex: "#00A160", usage: "Fresh" },
    ],
    story: "Burger King's 2021 retro rebrand ditched the glossy blue for warm browns, reds, and creams — colors of flame-grilled food. The palette feels honest and appetizing, evoking the actual colors of a burger. No artificial blues, just real food colors.",
    founded: "1954",
    website: "bk.com",
  },
  {
    slug: "red-bull",
    name: "Red Bull",
    industry: "Food & Beverage",
    colors: [
      { name: "Blue", hex: "#223971", usage: "Primary" },
      { name: "Red", hex: "#CC1E4A", usage: "Secondary" },
      { name: "Yellow", hex: "#FFC906", usage: "Sun/Background" },
      { name: "Silver", hex: "#C0C0C0", usage: "Can" },
      { name: "Dark Blue", hex: "#1E2C5A", usage: "Dark Variant" },
    ],
    story: "Red Bull's two charging bulls against a yellow sun symbolize energy, power, and adrenaline. The blue-silver can was designed to look different from every other drink on the shelf — and it worked. The color scheme transcended beverages into F1, esports, and extreme sports.",
    founded: "1987",
    website: "redbull.com",
  },

  // ─── Fashion & Retail (additional) ──────────────────
  {
    slug: "chanel",
    name: "Chanel",
    industry: "Fashion & Retail",
    colors: [
      { name: "Black", hex: "#000000", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Gold", hex: "#B9975B", usage: "Accent" },
      { name: "Cream", hex: "#F5F0E8", usage: "Surface" },
      { name: "Beige", hex: "#C8B89B", usage: "Secondary" },
    ],
    story: "Coco Chanel declared 'black has it all' — and her brand proves it. The interlocking CC logo in black and white is the epitome of luxury minimalism. Gold accents represent the chains and clasps of the iconic 2.55 bag. Less color = more prestige.",
    founded: "1910",
    website: "chanel.com",
  },
  {
    slug: "louis-vuitton",
    name: "Louis Vuitton",
    industry: "Fashion & Retail",
    colors: [
      { name: "Brown", hex: "#6B4226", usage: "Monogram" },
      { name: "Gold", hex: "#CFB370", usage: "Logo/Accent" },
      { name: "Tan", hex: "#D2B48C", usage: "Leather" },
      { name: "Black", hex: "#1A1A1A", usage: "Text" },
      { name: "Cream", hex: "#F3E9DC", usage: "Background" },
    ],
    story: "Louis Vuitton's brown and gold is the most recognizable luxury pattern on Earth. The monogram canvas was created in 1896 to prevent counterfeiting. The warm brown says heritage and craftsmanship, while gold whispers wealth without shouting it.",
    founded: "1854",
    website: "louisvuitton.com",
  },
  {
    slug: "zara",
    name: "Zara",
    industry: "Fashion & Retail",
    colors: [
      { name: "Black", hex: "#000000", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Gray", hex: "#999999", usage: "Secondary" },
      { name: "Warm White", hex: "#F4F4F4", usage: "Surface" },
      { name: "Silver", hex: "#C0C0C0", usage: "Accent" },
    ],
    story: "Zara's strictly monochrome palette lets the clothes be the color. The 2019 logo redesign with tightly kerned serif letters says editorial fashion. No color in the brand = every color in the collection. It's a gallery, not a carnival.",
    founded: "1975",
    website: "zara.com",
  },

  // ─── Automotive (additional) ────────────────────────
  {
    slug: "bmw",
    name: "BMW",
    industry: "Automotive",
    colors: [
      { name: "Blue", hex: "#1C69D4", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Logo/Background" },
      { name: "Black", hex: "#000000", usage: "Text" },
      { name: "Silver", hex: "#A8A8A8", usage: "Secondary" },
      { name: "M Red", hex: "#E31937", usage: "M Performance" },
    ],
    story: "BMW's blue and white roundel represents the Bavarian flag — though the popular myth says it's a spinning propeller (BMW started making aircraft engines). The M Sport's red-blue-purple stripes are among the most coveted badges in automotive culture.",
    founded: "1916",
    website: "bmw.com",
  },
  {
    slug: "porsche",
    name: "Porsche",
    industry: "Automotive",
    colors: [
      { name: "Black", hex: "#000000", usage: "Primary" },
      { name: "Red", hex: "#D5001C", usage: "Accent" },
      { name: "Gold", hex: "#C5A653", usage: "Crest" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Silver", hex: "#9E9E9E", usage: "Secondary" },
    ],
    story: "The Porsche crest combines the Stuttgart horse with Baden-Württemberg antlers — black and red from the German state's coat of arms. The gold communicates legacy and prestige. Every detail of the crest says engineering excellence and racing heritage.",
    founded: "1931",
    website: "porsche.com",
  },
  {
    slug: "lamborghini",
    name: "Lamborghini",
    industry: "Automotive",
    colors: [
      { name: "Gold", hex: "#DDB321", usage: "Primary" },
      { name: "Black", hex: "#000000", usage: "Background" },
      { name: "White", hex: "#FFFFFF", usage: "Text" },
      { name: "Yellow", hex: "#FFD100", usage: "Iconic Paint" },
      { name: "Silver", hex: "#C0C0C0", usage: "Accent" },
    ],
    story: "Lamborghini's gold and black palette was inspired by founder Ferruccio Lamborghini's zodiac sign — Taurus, the bull. Gold represents the raging bull's power, while black is the arena. The brand's most iconic car colors — Giallo Midas, Verde Scandal — push boundaries, just like the cars.",
    founded: "1963",
    website: "lamborghini.com",
  },

  // ─── Sports ─────────────────────────────────────────
  {
    slug: "nba",
    name: "NBA",
    industry: "Sports",
    colors: [
      { name: "Blue", hex: "#1D428A", usage: "Primary" },
      { name: "Red", hex: "#C8102E", usage: "Secondary" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Silver", hex: "#9EA2A2", usage: "Accent" },
      { name: "Black", hex: "#000000", usage: "Text" },
    ],
    story: "The NBA's red, white, and blue was chosen in 1969 to evoke the American flag and MLB's similar palette. Jerry West's silhouette (though officially denied) in white against the red-and-blue shield is one of sport's most recognized logos. The colors say patriotism and prestige.",
    founded: "1946",
    website: "nba.com",
  },
  {
    slug: "nfl",
    name: "NFL",
    industry: "Sports",
    colors: [
      { name: "Blue", hex: "#003069", usage: "Primary" },
      { name: "Red", hex: "#D50A0A", usage: "Accent" },
      { name: "White", hex: "#FFFFFF", usage: "Stars/Background" },
      { name: "Silver", hex: "#A5ACAF", usage: "Shield" },
      { name: "Dark", hex: "#13264D", usage: "Dark Variant" },
    ],
    story: "The NFL shield's deep blue and red represent the strength and intensity of American football. The 8 stars represent the 8 original divisions. The color palette is designed to look powerful on everything from stadiums to screens — projecting authority and tradition.",
    founded: "1920",
    website: "nfl.com",
  },
  {
    slug: "premier-league",
    name: "Premier League",
    industry: "Sports",
    colors: [
      { name: "Purple", hex: "#38003C", usage: "Primary" },
      { name: "Cyan", hex: "#00FF87", usage: "Accent" },
      { name: "Magenta", hex: "#E90052", usage: "Secondary" },
      { name: "Yellow", hex: "#FFF200", usage: "Highlight" },
      { name: "Dark Purple", hex: "#2D0032", usage: "Background" },
    ],
    story: "The Premier League's purple and neon green rebrand in 2016 was a bold departure from traditional sports branding. Purple represents royalty and prestige — fitting for the world's richest football league. The electric green adds energy and modernity, making it pop on broadcast.",
    founded: "1992",
    website: "premierleague.com",
  },
  {
    slug: "ufc",
    name: "UFC",
    industry: "Sports",
    colors: [
      { name: "Red", hex: "#D20A0A", usage: "Primary" },
      { name: "Black", hex: "#000000", usage: "Background" },
      { name: "White", hex: "#FFFFFF", usage: "Text" },
      { name: "Gold", hex: "#C1A14F", usage: "Championship" },
      { name: "Gray", hex: "#2D2D2D", usage: "Surface" },
    ],
    story: "UFC's red and black screams combat — aggression, intensity, and raw power. Gold is reserved for championship belts and title fights, adding prestige to the brutality. The minimal palette keeps the brand feeling dangerous and uncompromising.",
    founded: "1993",
    website: "ufc.com",
  },

  // ─── Health & Beauty ────────────────────────────────
  {
    slug: "dove",
    name: "Dove",
    industry: "Health & Beauty",
    colors: [
      { name: "Blue", hex: "#0E3E85", usage: "Primary" },
      { name: "Gold", hex: "#B8860B", usage: "Logo/Premium" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Cream", hex: "#F5F0E8", usage: "Soft Background" },
      { name: "Light Blue", hex: "#5B9BD5", usage: "Accent" },
    ],
    story: "Dove's white and gold represent purity, gentleness, and premium quality. The dove silhouette in gold communicates peace and softness. Their blue packaging builds trust. The entire palette says: this is gentle, this is caring, this is real beauty.",
    founded: "1957",
    website: "dove.com",
  },
  {
    slug: "loreal",
    name: "L'Oréal",
    industry: "Health & Beauty",
    colors: [
      { name: "Black", hex: "#000000", usage: "Primary" },
      { name: "Gold", hex: "#C09853", usage: "Accent" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Red", hex: "#FF0000", usage: "L'Oréal Paris" },
      { name: "Purple", hex: "#46166B", usage: "Youth Code" },
    ],
    story: "L'Oréal's black and gold is pure Parisian luxury — the same palette as haute couture and fine champagne. 'Because you're worth it' becomes visual through gold accents. The red for L'Oréal Paris sub-brand adds passion and French sophistication.",
    founded: "1909",
    website: "loreal.com",
  },

  // ─── Travel & Airlines ──────────────────────────────
  {
    slug: "emirates",
    name: "Emirates",
    industry: "Travel & Airlines",
    colors: [
      { name: "Red", hex: "#D71921", usage: "Primary" },
      { name: "Gold", hex: "#C8A951", usage: "Premium" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Dark Red", hex: "#8B0000", usage: "Accent" },
      { name: "Cream", hex: "#F5F1E3", usage: "Surface" },
    ],
    story: "Emirates' red and gold represents the luxury of Arabian hospitality and the red of the UAE flag. Gold signals first-class opulence — their A380 showers and private suites. The calligraphy logo bridges tradition with modern luxury aviation.",
    founded: "1985",
    website: "emirates.com",
  },
  {
    slug: "booking",
    name: "Booking.com",
    industry: "Travel & Airlines",
    colors: [
      { name: "Navy Blue", hex: "#003580", usage: "Primary" },
      { name: "Blue", hex: "#0071C2", usage: "CTA" },
      { name: "Yellow", hex: "#FEBB02", usage: "Genius/Deals" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Dark", hex: "#1A1A2E", usage: "Text" },
    ],
    story: "Booking.com's deep navy blue communicates trust and reliability in the travel industry. The signature yellow badge system (Genius deals) creates urgency and signals savings. Their relentless A/B testing even optimized the exact shade of blue for conversions.",
    founded: "1996",
    website: "booking.com",
  },

  // ─── Media ──────────────────────────────────────────
  {
    slug: "bbc",
    name: "BBC",
    industry: "Media",
    colors: [
      { name: "Black", hex: "#000000", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Logo/Background" },
      { name: "Blue", hex: "#1A3A5C", usage: "BBC News" },
      { name: "Red", hex: "#BB1919", usage: "BBC One" },
      { name: "Green", hex: "#006633", usage: "BBC Earth" },
    ],
    story: "The BBC's three white-on-black blocks are a masterclass in simplicity — immediately recognizable at any size. Each sub-brand gets its own color (news is blue for authority, sport is yellow for energy). The black foundation means the BBC always feels serious and trusted.",
    founded: "1922",
    website: "bbc.com",
  },
  {
    slug: "hbo",
    name: "HBO",
    industry: "Media",
    colors: [
      { name: "Black", hex: "#000000", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Logo" },
      { name: "Purple", hex: "#6B3FA0", usage: "HBO Max" },
      { name: "Blue", hex: "#0A2744", usage: "Dark Surface" },
      { name: "Gold", hex: "#C8A654", usage: "Premium" },
    ],
    story: "HBO's stark black background says premium content — you're paying for something worth the darkness. The iconic TV static intro conditioned a generation to associate HBO with quality. The Max rebrand introduced purple to feel more modern while keeping the prestige.",
    founded: "1972",
    website: "hbo.com",
  },

  // ─── Finance (additional) ───────────────────────────
  {
    slug: "visa",
    name: "Visa",
    industry: "Finance",
    colors: [
      { name: "Blue", hex: "#1A1F71", usage: "Primary" },
      { name: "Gold", hex: "#F7B600", usage: "Accent" },
      { name: "White", hex: "#FFFFFF", usage: "Background" },
      { name: "Light Blue", hex: "#1565C0", usage: "Digital" },
      { name: "Dark Blue", hex: "#15195A", usage: "Dark Variant" },
    ],
    story: "Visa's blue and gold represents the meeting of sky (blue) and sun (gold) — Dee Hock chose these colors because they symbolize universal acceptance. Blue signals trust and security, gold signals premium value. Visa is accepted in 200+ countries, and the colors had to work everywhere.",
    founded: "1958",
    website: "visa.com",
  },
  {
    slug: "robinhood",
    name: "Robinhood",
    industry: "Finance",
    colors: [
      { name: "Green", hex: "#00C805", usage: "Primary/Gain" },
      { name: "Black", hex: "#1E2124", usage: "Background" },
      { name: "White", hex: "#FFFFFF", usage: "Text" },
      { name: "Red", hex: "#FF5000", usage: "Loss" },
      { name: "Yellow", hex: "#FFDC00", usage: "Gold Tier" },
    ],
    story: "Robinhood's green means one thing: your portfolio is up. Green = money = gains. The dark UI mimics professional trading terminals, making everyday investors feel like Wall Street traders. The name and the green together say: we're taking from the rich and giving to you.",
    founded: "2013",
    website: "robinhood.com",
  },

  // ─── Entertainment (additional) ─────────────────────
  {
    slug: "disney",
    name: "Disney",
    industry: "Entertainment",
    colors: [
      { name: "Blue", hex: "#113CCF", usage: "Primary" },
      { name: "White", hex: "#FFFFFF", usage: "Logo/Castle" },
      { name: "Gold", hex: "#F9D71C", usage: "Magic/Stars" },
      { name: "Purple", hex: "#4B2E83", usage: "Accent" },
      { name: "Red", hex: "#E31837", usage: "Mickey" },
    ],
    story: "Disney's blue is the twilight sky over Cinderella's castle — the moment when magic happens. Gold represents fairy dust, wishes, and stars. The palette is dreamlike by design. Walt Disney once said color should make people 'feel' — and Disney's palette makes you feel like a kid again.",
    founded: "1923",
    website: "disney.com",
  },
  {
    slug: "hulu",
    name: "Hulu",
    industry: "Entertainment",
    colors: [
      { name: "Green", hex: "#1CE783", usage: "Primary" },
      { name: "Black", hex: "#040405", usage: "Background" },
      { name: "White", hex: "#FFFFFF", usage: "Text" },
      { name: "Gray", hex: "#272C30", usage: "Surface" },
      { name: "Dark Gray", hex: "#1B1F23", usage: "Card" },
    ],
    story: "Hulu's vivid green on black was chosen to stand apart from Netflix's red and Amazon's blue. The bright green feels alive and fresh — like clicking 'play' on something new. Against the dark UI, it's impossible to miss. Hulu found the last unclaimed streaming color.",
    founded: "2007",
    website: "hulu.com",
  },
];

export function getBrandBySlug(slug: string): Brand | undefined {
  return BRANDS.find((b) => b.slug === slug);
}

export function getBrandsByIndustry(industry: string): Brand[] {
  if (industry === "All") return BRANDS;
  return BRANDS.filter((b) => b.industry === industry);
}
